spring:
  application:
<<<<<<< HEAD
    name: hms_local
  datasource:
    url: jdbc:mysql://localhost:3306/hms_local
    username: root
    password: Wefive55@
=======
    name: HospitalManagement
  datasource:
    url: jdbc:mysql://:3306/hms
    username: client_user
    password: password123
>>>>>>> da1de7d8ea7694e19bb4d2a962995d8621fda041
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8087

